version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./data/db:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - bridgenet

  oauth2_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-oauth2-server
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 9000:8080
    networks:
      - bridgenet

networks:
  bridgenet:
